version: "2"

services:
  db:
    image: kartoza/postgis:9.6-2.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASS: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DBNAME: 'test'
      POSTGRES_MULTIPLE_EXTENSIONS: "postgis"
    volumes:
      - ./var/lib/postgresql/data
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: "db:5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "postgres"
      POSTGRES_DBNAME: "test"
    expose:
      - 8080
    ports:
      - 8080:8080
