version: '3'

services:
  pgadmin4:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
  db:
    image: kartoza/postgis:9.6-2.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASS: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DBNAME: 'test'
      POSTGRES_MULTIPLE_EXTENSIONS: "postgis"
    expose:
      - 5432
    volumes:
      - ./var/lib/postgresql/data
  tf:
    build:
      dockerfile: Dockerfile
      context: ./tensorflowServe
    ports:
      - "8500:8500"
      - "8501:8501"
    command: --model_config_file=/config/config.conf

  backend:
    restart: unless-stopped
    build:
      context: ./backend
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test"
    depends_on:
      - db
      - tf
    ports:
      - "8000:8000"
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      args:
          FRONTEND_ENV: dev
