from Resources.generalKitResource import KitResource
from Resources.measurementResource import MeasurementResource
from Resources.sensorResource import SensorResource
from Resources.valueResource import ValueResource
from Resources.debugResource import DebugResource
from Resources.geoResource import GeoResource