default_context:
  project_name: 'd4c_api'
  project_slug: 'd4c_api'
  domain_main: 'd4c_api.com'
  domain_staging: 'stag.d4c_api.com'
  docker_swarm_stack_name_main: 'd4c_api-com'
  docker_swarm_stack_name_staging: 'stag-d4c_api-com'
  secret_key: 'd4capi'
  first_superuser: 'admin@d4c_api.com'
  first_superuser_password: 'admin'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.d4c_api.com, https://stag.d4c_api.com, https://d4c_api.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@d4c_api.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@d4c_api.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'd4c_api.com'
  traefik_constraint_tag_staging: 'stag.d4c_api.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
