"""File Type  Constraint deleted

Revision ID: 100d9edc388a
Revises: 6482584afc79
Create Date: 2019-09-06 20:17:14.697116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100d9edc388a'
down_revision = '6482584afc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )

    # ### end Alembic commands ###


def downgrade():

    op.drop_table('dbfile')
    # ### end Alembic commands ###
