"""File Type Added

Revision ID: 2f8890edb6e2
Revises: 100d9edc388a
Create Date: 2019-09-06 20:35:28.288378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8890edb6e2'
down_revision = '100d9edc388a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dbfile_data_key', 'dbfile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dbfile_data_key', 'dbfile', ['data'])

    # ### end Alembic commands ###
