"""Inference  Type Added

Revision ID: 6b499b7fc09f
Revises: 2f8890edb6e2
Create Date: 2019-09-06 20:44:17.179518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b499b7fc09f'
down_revision = '2f8890edb6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Enum('air_conditioner', 'car_horn', 'children_playing', 'dog_bark', 'drilling', 'engine_idling', 'gun_shot', 'jackhammer', 'siren', 'street_music', name='labelsenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=40), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['dbfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('dbfile', 'data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_kit_geom', 'kit', ['geom'], unique=False)
    op.alter_column('dbfile', 'data',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    op.drop_table('inference')
    op.drop_table('labels')
    # ### end Alembic commands ###
