"""Added index

Revision ID: 5f203ae0e4c1
Revises: cee530d427a0
Create Date: 2019-10-21 18:18:24.503796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f203ae0e4c1'
down_revision = 'cee530d427a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_label_id'), 'label', ['id'], unique=False)
    op.create_index(op.f('ix_label_label'), 'label', ['label'], unique=True)
    op.drop_constraint('label_label_key', 'label', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('label_label_key', 'label', ['label'])
    op.drop_index(op.f('ix_label_label'), table_name='label')
    op.drop_index(op.f('ix_label_id'), table_name='label')
    # ### end Alembic commands ###
