"""1 to many relationship added for label

Revision ID: cee530d427a0
Revises: 60ab7355bc44
Create Date: 2019-10-21 17:43:20.370794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee530d427a0'
down_revision = '60ab7355bc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbfile', sa.Column('label_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dbfile', 'label', ['label_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dbfile', type_='foreignkey')
    op.drop_column('dbfile', 'label_id')
    # ### end Alembic commands ###
