version: '3'

services:
  pgadmin4:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
  db:
    image: kartoza/postgis:9.6-2.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASS: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DBNAME: 'test'
      POSTGRES_MULTIPLE_EXTENSIONS: "postgis"
    expose:
      - 5432
    volumes:
      - ./var/lib/postgresql/data
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test"
    depends_on:
      - db
    ports:
      - "8000:8000"
